config/routes.rb
ResultAlertSystem::Application.routes.draw do

  match 'register' => 'pages#register'
  match 'result' => 'pages#result'
  match 'profile' => 'pages#profile'
  resource :students
  resource :results
  resource :sessions
  match 'logout' => 'sessions#destroy'

  root :to => 'pages#index'

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :student
  attr_accessor :matric_no, :student_id
  attr_accessible :course_name, :course_title, :matric_no, :student_id, :score
  validates_presence_of :course_name, :course_title, :matric_no, :score
  validate :id_by_matric_number?

  def student
    Student.find_by_matric_no(matric_no)
  end

  def id_by_matric_number?
    if student.nil?
      errors.add(:matric_no, "no record of the matric number found")
    else
      student_id = student.id 
    end
  end
end

app/models/sms.rb
require 'yaml'
require "net/http"
require "uri"
require 'cgi'
class Sms
  def self.load_config
    YAML.load_file File.expand_path("#{Rails.root}/config/config.yml", __FILE__)
  end

  def self.execute(number,message)
    params = {"u" => self.load_config['sms_gateway']['username'],
              "p" => self.load_config['sms_gateway']['password'],
              "s" => self.load_config['sms_gateway']['sender'],
              "r" => self.msisdn_corrector(number),
              "m" => message,
              "t" => 1}

    url = self.load_config['sms_gateway']['url'] + "?u=" + params["u"] + "&p=" + params["p"] + "&s=" + params["s"] + "&r=" + params["r"] + "&m=" + URI.encode(params["m"]) + "&t=" + params["t"].to_s
    response = Net::HTTP.get_response(URI.parse(url))
    case
    when response.body.to_s.include?("00")
      Rails.logger.info "Successful"
    when response.body.to_s.include?("11")
      Rails.logger.info "Missing username"
    when response.body.to_s.include?("12")
      Rails.logger.info "Missing password"
    when response.body.to_s.include?("13")
      Rails.logger.info "Missing receipient"
    when response.body.to_s.include?("14")
      Rails.logger.info "Missing sender id"
    when response.body.to_s.include?("15")
      Rails.logger.info "Missing message"
    when response.body.to_s.include?("21")
      Rails.logger.info "Sender Id too long"
    when response.body.to_s.include?("22")
      Rails.logger.info "INVALID RECIPIENT"
    when response.body.to_s.include?("23")
      Rails.logger.info "INVALID MESSAGE"
    when response.body.to_s.include?("31")
      Rails.logger.info "INVALID USERNAME"
    when response.body.to_s.include?("32")
      Rails.logger.info "INVALID PASSWORD"
    when response.body.to_s.include?("33")
      Rails.logger.info "INVALID LOGIN"
    when response.body.to_s.include?("34")
      Rails.logger.info "ACCOUNT DISABLED"
    when response.body.to_s.include?("41")
      Rails.logger.info "INSUFFICIENT CREDIT"
    when response.body.to_s.include?("51")
      Rails.logger.info "GATEWAY UNREACHABLE"
    when response.body.to_s.include?("52")
      Rails.logger.info "SYSTEM ERROR"
    else
      Rails.logger.info "Unrecoverable error"
    end
  end

  def self.msisdn_corrector(msisdn)
    case 
    when msisdn[0] == "0"
      msisdn[0] = "234"
    when ((msisdn[0] != "0") && msisdn.size == 10)
      msisdn = "234" + msisdn
    when ((msisdn[0] != "0") && msisdn.size != 11)
      msisdn = msisdn
    else
    end
    msisdn
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :results
  has_secure_password
  validates_presence_of :password, :on => :create
  attr_accessible :email, :matric_no, :name, :phone_number, :password, :password_confirmation
  validates_presence_of :email, :matric_no, :name, :phone_number
  validates_uniqueness_of :matric_no  
  validates :email, :format => { :with => %r{.+@.+\..+}, :message => "is not a valid email address" }
  validates :phone_number, :format => { :with => %r{0\d{10}}, :message => "it should be of the format 08030000001" }

  def matric_no=(value)
    value.downcase
    self[:matric_no] = value
  end

  def random_password
    Array.new(10).map { (32 + rand(90)).chr }.join
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def current_student
    @current_student ||= Student.find(session[:student_id]) if session[:student_id]
  end

  helper_method :current_student
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :require_login, only: :profile
  def index
  end

  def register
  end

  def result
  end

  def profile
  end

  private
  def require_login
    if current_student.nil?
      redirect_to root_url
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def new
    @result = Result.new
  end

  def create
    @result = Result.new(params[:result])
    @student = student(params[:result]["matric_no"].downcase)
    if @student.nil?
      redirect_to(result_path, :notice => "Student Matric number not found")
      return nil
    else
      @result[:student_id] = @student.id
    end

    if @result.save
      redirect_to(root_path, :notice => 'Result has been posted successfully')
      begin
        StudentMailer.result_email(@student).deliver 
        Sms.execute(@student.phone_number, "You scored #{@result.score} in #{@result.course_title} #{@result.course_name}")
      rescue Net::SMTPAuthenticationError => e1
        Rails.logger.info e1.backtrace
        redirect_to(root_path, :notice => 'Result has been posted, however there was error sending email')
      rescue => e
        Rails.logger.info e.backtrace
        redirect_to(root_path, :notice => 'Result has been posted, however there was error sending sms')
      end
    else
      redirect_to(result_path, :alert => @result.errors)
    end
  end

  def show
  end

  private
  def student(matric_no)
    student = Student.find_by_matric_no(matric_no)
    student.nil? ? nil : student
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if params[:session][:matric_no].nil? || params[:session][:matric_no].empty?
      redirect_to register_path, :alert =>"Please enter a valid Matric No, or Register"
    else
      student = Student.find_by_matric_no(params[:session][:matric_no].downcase)
      if student && student.authenticate(params[:session][:password])
        session[:student_id] = student.id
        redirect_to profile_path, :notice => "Logged in!"
      else
        redirect_to root_url, :alert =>"Invalid Matric No or Password"
      end
    end
  end

  def show
  end

  def destroy
    session[:student_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(params[:student])
    @student[:matric_no] = @student[:matric_no].downcase
    if @student.save
      session[:student_id] = @student.id
      begin
        StudentMailer.welcome_email(@student).deliver 
        Sms.execute(@student.phone_number, "#{@student.name}, you have successfully registered for the UNIABUJA student alert system")
        redirect_to(root_path, :notice => 'Your account has been created')
      rescue Net::SMTPAuthenticationError => e1
        Rails.logger.info e1.backtrace
        redirect_to(root_path, :notice => 'Your account has been created, however there was error sending email')
      rescue => e
        Rails.logger.info e.backtrace
        redirect_to(root_path, :notice => 'Your account has been created, however there was error sending sms')
      end
    else
      Rails.logger.info @student.errors.messages.inspect
      redirect_to(register_path, :alert => @student.errors)
    end
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    current_page?(path) ? "active" : ""
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Result Alert System", root_url, class: "brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class=<%=active_class(root_url)%>><%= link_to "Home", root_url  %></li>
          <li class=<%=active_class(register_path)%>><%= link_to "Register", register_path if current_student.nil? %></li>
          <li class=<%=active_class(profile_path)%>><%= link_to "Profile", profile_path unless current_student.nil? %></li>
          <li class=<%=active_class(result_path)%>><%= link_to "Post Result", result_path%></li>
        </ul>
        <% if current_student.nil? %>
          <%= form_for :session, :url => sessions_path, html: {class: "navbar-form pull-right"} do |f| %>
            <%= f.text_field :matric_no, class:"span2", placeholder:"Matric No" %>
            <%= f.password_field :password, class:"span2", placeholder:"Password" %>
            <%= f.submit "Sign in", class: "btn" %>
          <% end %>
        <% else %>
          <div class="pull-right" >
            <h5 class="welcome_user">Welcome! <%= current_student.name %> <%= link_to "logout", logout_path, class: "btn" %></h5>
            
          </div>
        <% end %>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Result Alert System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render template: 'layouts/_navbar' %>
    <div class="container">
      <% unless alert.nil? %>
        <div class="alert-message alert">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          <% if alert.respond_to?(:messages) %>
            The following errors occured:
            <% alert.messages.each do |k,v| %>
              <ul>
                <% unless k.eql?(:password_digest) %>
                  <li><%= "#{k.to_s.gsub("_", " ").capitalize} #{v.is_a?(Array) ? v.join(" and ") : v}"%></li>
                <% end %>
              </ul>
            <% end %>
          <% else %>
            <%= alert %>
          <% end %>
        </div>
      <% end %>
      <% unless notice.nil? %>
        <div class="success-message alert">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          <%= notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/index.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
    <%= image_tag "slide01.jpg" %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Register Today.</h1>
          <p class="lead">Register and get your results delivered to you in real time</p>
          <%= link_to "Register", register_path, class: "btn btn-large btn-primary" %>
        </div>
      </div>
    </div>
    <div class="item">
    <%= image_tag "slide02.jpg" %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Receive SMS.</h1>
          <p class="lead">Get SMS alert immediately your results are ready</p>
          <%= link_to "Join", register_path, class: "btn btn-large btn-primary" %>
        </div>
      </div>
    </div>
    <div class="item">
    <%= image_tag "slide03.jpg" %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Receive Emails.</h1>
          <p class="lead">Get emails with your full result details right on time</p>
          <%= link_to "Sign up today", register_path, class: "btn btn-large btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="carousel.html#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="right carousel-control" href="carousel.html#myCarousel" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

app/views/pages/profile.html.erb
<%= image_tag 'logo.jpg', class:"img-polaroid pull-right" %>

app/views/pages/register.html.erb
<div>
  <%= form_for(:student, :url => students_path, html: {:class => 'form-horizontal'}) do |f| %>
    <fieldset>
      <legend>Register</legend>
      <div class="control-group">
        <%= f.label :name, :class => "control-label", for: "inputName" %>
        <div class="controls">
          <%= f.text_field :name, :placeholder => "Name e.g Fawole John...", id: "inputName", size:'50' %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :email, :class => "control-label", for: "inputEmail" %>
        <div class="controls">
          <%= f.text_field :email, :placeholder => "Email e.g a@aol.com", id: "inputEmail" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :matric_no, :class => "control-label", for: "inputMatric" %>
        <div class="controls">
          <%= f.text_field :matric_no, :placeholder => "Matric number e.g 08283453", id: "inputMatric" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :phone_number, :class => "control-label", for: "inputPhone" %>
        <div class="controls">
          <%= f.text_field :phone_number, :placeholder => "Phone number here e.g 08030000001", id: "inputPhone" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :password, :class => "control-label", for: "inputPass" %>
        <div class="controls">
          <%= f.password_field :password, id: "inputPass" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :password_confirmation, :class => "control-label", for: "inputPassConf" %>
        <div class="controls">
          <%= f.password_field :password_confirmation, id: "inputPassConf" %>
        </div>
      </div>
      <%= f.submit "Register", class:"btn" %>
    </fieldset>
  <% end %>
</div>

app/views/pages/result.html.erb
<div>
  <%= form_for(:result, :url => results_path, html: {:class => 'form-horizontal'}) do |f| %>
    <fieldset>
      <legend>Post Result</legend>
      <div class="control-group">
        <%= f.label :course_name, :class => "control-label", for: "inputName" %>
        <div class="controls">
          <%= f.text_field :course_name, :placeholder => "e.g CSC 401", id: "inputName", size:'50' %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :course_title, :class => "control-label", for: "inputEmail" %>
        <div class="controls">
          <%= f.text_field :course_title, :placeholder => "e.g Introduction to Logic", id: "inputEmail", class:"input-xxlarge" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :matric_no, :class => "control-label", for: "inputMatric" %>
        <div class="controls">
          <%= f.text_field :matric_no, :placeholder => "Matric number e.g 08283453", id: "inputMatric" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :score, :class => "control-label", for: "inputScore" %>
        <div class="controls">
          <%= f.text_field :score, type: "number", id: "inputScore", class: "input-mini"%>
        </div>
      </div>
      <%= f.submit "Post Result", class:"btn" %>
    </fieldset>
  <% end %>
</div>